# Gleich und Wechselstrombrücken

In [67]:
import uncertainties as unc
from uncertainties import ufloat
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## Geräte Parameter

### 1.1 Berechnungen

Näherungsformel GLeichung 2.5. Widerstandsinkrement R_1 tauschen mit R_4 da $R_1R_4 = R_2R_3$ gilt



Abgleichbedingung

$$ 
\frac{R_1}{R_2} = \frac{R_3}{R_4}, \quad \frac{R_2}{R_1} = ratio \\
R_3 = R_4 \cdot ratio, \quad R_2 = \frac{R_1}{ratio}
$$

In [68]:
# Gegeben
UH = 3
# Zu Messen
deltaU = -30e-6
deltaR4 = 1
R1 = ufloat(3472,32) # Messergebnis +/- Garantiefehler im MB

In [69]:
def calcR(ratio):
    R4 = -(deltaR4 * UH) / (deltaU * (1+1/ratio)*(1+ratio))
    R3 = R4/ratio
    R2 = R1*ratio
    return {
        "Ratio": ratio,
        "R1": R1,
        "R2": R2,
        "R3": R3,
        "R4": R4
    }

data = [calcR(r) for r in [0.5, 1, 2]]
df1 = pd.DataFrame(data, columns=['Ratio', 'R1' ,'R2', 'R3', 'R4'])
print(df1.to_latex(
    index=False,
    formatters={
        "Ratio": "${:.1f}$".format,
        "R1": "${:.2uS}$".format,
        "R2": "${:.2uS}$".format,
        "R3": "${:.0f}$".format,
        "R4": "${:.0f}$".format
        }
    ))
df1

\begin{tabular}{rllrr}
\toprule
Ratio & R1 & R2 & R3 & R4 \\
\midrule
$0.5$ & $3472(32)$ & $1736(16)$ & $44444$ & $22222$ \\
$1.0$ & $3472(32)$ & $3472(32)$ & $25000$ & $25000$ \\
$2.0$ & $3472(32)$ & $6944(64)$ & $11111$ & $22222$ \\
\bottomrule
\end{tabular}

   Ratio         R1                 R2            R3            R4
0    0.5  3472+/-32          1736+/-16  44444.444444  22222.222222
1    1.0  3472+/-32          3472+/-32  25000.000000  25000.000000
2    2.0  3472+/-32  (6.94+/-0.06)e+03  11111.111111  22222.222222

### 1.2 Berechnungen

R2 R3 Grob,
R4 fein,
R1 berechnen

In [70]:
def calcR(ratio, R2, R3, R4):
    R1 = R2*R3/R4
    return {
        "Ratio": ratio,
        "R2": R2,
        "R3": R3,
        "R4": R4,
        "R1": R1
    }

data = [ calcR(r,R2,R3,R4) for r,R2,R3,R4 in [
        (0.5,ufloat(2200,22),   ufloat(47000,470), ufloat(29690,29.69+0.025)),
        (0.5,ufloat(2200,22),   ufloat(22000,220), ufloat(13870,13.87+0.025)),
        (1,  ufloat(4700,47),   ufloat(22000,220), ufloat(29680,29.68+0.025)),
        (1,  ufloat(4700,47),   ufloat(10000,100), ufloat(13510,13.51+0.025)),
        (2,  ufloat(10000,100), ufloat(10000,100), ufloat(29050,29.05+0.025)),
        (2,  ufloat(10000,100), ufloat(4700,47), ufloat(13600,13.6+0.025))
    ]]
df2 = pd.DataFrame(data, columns=['Ratio' ,'R2', 'R3', 'R4', 'R1'])
print(df2.to_latex(
    float_format="{:.2f}".format,
    formatters={
        "R1": "{:.2uS}".format,
        "R2": "{:.2uS}".format,
        "R3": "{:.2uS}".format,
        "R4": "{:.2uS}".format
        }
    ))
df2

\begin{tabular}{lrllll}
\toprule
 & Ratio & R2 & R3 & R4 & R1 \\
\midrule
0 & 0.50 & 2200(22) & 4.700(47)e+04 & 29690(30) & 3483(49) \\
1 & 0.50 & 2200(22) & 2.200(22)e+04 & 13870(14) & 3490(49) \\
2 & 1.00 & 4700(47) & 2.200(22)e+04 & 29680(30) & 3484(49) \\
3 & 1.00 & 4700(47) & 1.000(10)e+04 & 13510(14) & 3479(49) \\
4 & 2.00 & 1.000(10)e+04 & 1.000(10)e+04 & 29050(29) & 3442(49) \\
5 & 2.00 & 1.000(10)e+04 & 4700(47) & 13600(14) & 3456(49) \\
\bottomrule
\end{tabular}

,Ratio,R2,R3,R4,R1
0,0.5,2200+/-22,(4.70+/-0.05)e+04,29690+/-30,(3.48+/-0.05)e+03
1,0.5,2200+/-22,(2.200+/-0.022)e+04,13870+/-14,(3.49+/-0.05)e+03
2,1.0,(4.70+/-0.05)e+03,(2.200+/-0.022)e+04,29680+/-30,(3.48+/-0.05)e+03
3,1.0,(4.70+/-0.05)e+03,(1.000+/-0.010)e+04,13510+/-14,(3.48+/-0.05)e+03
4,2.0,(1.000+/-0.010)e+04,(1.000+/-0.010)e+04,29050+/-29,(3.44+/-0.05)e+03
5,2.0,(1.000+/-0.010)e+04,(4.70+/-0.05)e+03,13600+/-14,(3.46+/-0.05)e+03

### 1.3 Empfindlichkeit

In [71]:
deltaR1 = 10.1 # 5...10 Ohm
U0min = 30e-6 # Kleinst mögliche spannungsänderung -> Auflösung MB

#### Berechnung mit $U_0$

Diese Annäherung gilt für sehr kleine Abweichungen
$$
E = \frac{\partial U_0}{\partial\frac{\Delta R_1}{R_1}} \approx \frac{U_0}{\frac{\Delta R_1}{R_1}}
$$

absolut Kleinste Widerstandsänderung, die am Messgerät erkannt wird

$$
\Delta R_{1,\min} = \frac{\Delta R_1\cdot U_{0,\min}}{U_0}
$$

relativ Kleinste Widerstandsänderung, die am Messgerät erkannt wird

$$
\frac{\Delta R_{1,min}}{R_1} = \frac{\Delta R_1\cdot U_{0,\min}}{U_0\cdot R_1}
$$

In [85]:
# Zu Messen
U0 = [
	ufloat(-2.2e-3, -2.2e-3*0.0005+3*10e-6),
	ufloat(-2.5e-3, -2.3e-3*0.0005+3*10e-6),
	ufloat(-1.6e-3, -1.6e-3*0.0005+3*10e-6),
]

# Berechnung
relR1 = deltaR1/df2["R1"][[0,2,4]]
E = U0/relR1
deltaR1min = [deltaR1*U0min/u for u in U0]
relDeltaR1min = deltaR1min/df2["R1"][[0,2,4]]

data = {
	"U0": U0,
    "E": E,
    "deltaR1min": deltaR1min,
    "relDeltaR1min": relDeltaR1min
}

df3 = pd.DataFrame(data, columns=['U0', 'E', 'deltaR1min', 'relDeltaR1min'])
print(df3.to_latex(
    float_format="{:.2f}".format,
    formatters={
		"U0": "{:.1uS}".format,
        "E": "{:.2uS}".format,
        "deltaR1min": "{:.2uS}".format,
        "relDeltaR1min": "{:.2uS}".format,
        }
    ))
df3

\begin{tabular}{lllll}
\toprule
 & U0 & E & deltaR1min & relDeltaR1min \\
\midrule
0 & -0.00220(3) & -0.759(15) & -0.1377(18) & -3.955(76)e-05 \\
2 & -0.00250(3) & -0.862(16) & -0.1212(14) & -3.479(64)e-05 \\
4 & -0.00160(3) & -0.545(13) & -0.1894(35) & -5.50(13)e-05 \\
\bottomrule
\end{tabular}

                     U0               E        deltaR1min       relDeltaR1min
0  -0.002200+/-0.000029  -0.759+/-0.015  -0.1377+/-0.0018  (-3.95+/-0.08)e-05
2  -0.002500+/-0.000029  -0.862+/-0.016  -0.1212+/-0.0014  (-3.48+/-0.06)e-05
4  -0.001600+/-0.000029  -0.545+/-0.013  -0.1894+/-0.0035  (-5.50+/-0.13)e-05

#### Berechnung aus Brückendaten

In [73]:
Uh = 3
R1 = df2["R1"][[0,2,4]]
R2 = df2["R2"][[0,2,4]]
R3 = df2["R3"][[0,2,4]]
R4 = df2["R4"][[0,2,4]]

E = -Uh / ((1+R2/R1)*(1+R3/R4))
relDeltaR1min = U0min / E
deltaR1min = R1 * U0min / E

data = {
	"E": E,
	"deltaR1min": deltaR1min,
	"relDeltaR1min": relDeltaR1min
}
df4 = pd.DataFrame(data, columns=['E', 'deltaR1min', 'relDeltaR1min'])
print(df4.to_latex(
	float_format="{:.2f}".format,
	formatters={
		"E": "{:.2uS}".format,
		"deltaR1min": "{:.2uS}".format,
		"relDeltaR1min": "{:.2uS}".format,
		}
	))
df4

\begin{tabular}{llll}
\toprule
 & E & deltaR1min & relDeltaR1min \\
\midrule
0 & -0.7118(16) & -0.1468(23) & -4.2147(96)e-05 \\
2 & -0.7334(11) & -0.1425(19) & -4.0903(61)e-05 \\
4 & -0.5715(28) & -0.1807(20) & -5.249(26)e-05 \\
\bottomrule
\end{tabular}

                  E        deltaR1min         relDeltaR1min
0  -0.7118+/-0.0016  -0.1468+/-0.0023  (-4.215+/-0.010)e-05
2  -0.7334+/-0.0011  -0.1425+/-0.0019  (-4.090+/-0.006)e-05
4  -0.5715+/-0.0028  -0.1807+/-0.0020  (-5.249+/-0.026)e-05